package com.mini.workshop.template.orchestratorresponseentity;

public enum MessageTypes {

    MESSAGE_TYPES_TEXT, MESSAGE_TYPES_ATTACHMENT, MESSAGE_TYPES_LOCATION, MESSAGE_TYPES_LISTCARD, MESSAGE_TYPES_BUTTONLINK,
    MESSAGE_TYPE_CARDGROUP,MESSAGE_TYPES_VOICE, MESSAGE_CHAT_ACTION;

}
